### ISSUE TITLE
Add visual monitor

### ISSUE THREAD

**Issue by amitaibu** [Gizra/apester-shoov#1]
http://renderer.qmerce.com/interaction/55b117d6c902770806bf2097

test should include hover over first item

![apester_interactive_content](https://cloud.githubusercontent.com/assets/125707/10360468/85a88ee0-6da9-11e5-9f82-72ee3212a74d.jpg)

**Comment by amitaibu** [comment]
@DavidKohav can you create a Shoov link where the top circle is missing

![apester_interactive_content-2](https://cloud.githubusercontent.com/assets/125707/10365014/9e0011e2-6dc8-11e5-9bf8-26f5213a960e.jpg)

**Comment by mldk-tech** [comment]
@amitaibu - 
https://app.shoov.io/#/screenshots/12519
